project:
  type: website
  output-dir: docs

website:
  title: "NL Salmon resource predictions"
  navbar:
    left:
      - text: "Home" 
        href: index.qmd
      - text: "Watershed predictions"
        menu:
        - text: "Strait of Belle Isle - South Shore watershed"
          href: "map_Strait%20of%20Belle%20Isle%20-%20South%20Shore.html"
        - text: "Hare Bay watershed"
          href: "map_Hare%20Bay.html"
        - text: "St. John Bay watershed"
          href: "map_St.%20John%20Bay.html"
        - text: "Canada Bay watershed"
          href: "map_Canada%20Bay.html"
        - text: "Portland Creek Pond watershed"
          href: "map_Portland%20Creek%20Pond.html"
        - text: "Western White Bay watershed"
          href: "map_Western%20White%20Bay.html"
        - text: "Southern and Eastern White Bay watershed"
          href: "map_Southern%20and%20Eastern%20White%20Bay.html"
        - text: "Bonne Bay watershed"
          href: "map_Bonne%20Bay.html"
        - text: "Port au Port Bay watershed"
          href: "map_Port%20au%20Port%20Bay.html"
        - text: "Humber - Upper watershed"
          href: "map_Humber%20-%20Upper.html"
        - text: "Humber - Lower watershed"
          href: "map_Humber%20-%20Lower.html"
        - text: "Western Notre Dame Bay watershed"
          href: "map_Western%20Notre%20Dame%20Bay.html"
        - text: "Red Indian Lake watershed"
          href: "map_Red%20Indian%20Lake.html"
        - text: "Exploits watershed"
          href: "map_Exploits.html"
        - text: "Southwestern Notre Dame Bay watershed"
          href: "map_Southwestern%20Notre%20Dame%20Bay.html"
        - text: "Gander watershed"
          href: "map_Gander.html"
        - text: "Northwestern Bonavista Bay watershed"
          href: "map_Northwestern%20Bonavista%20Bay.html"
        - text: "Southern and Eastern Bonavista Bay watershed"
          href: "map_Southern%20and%20Eastern%20Bonavista%20Bay.html"
        - text: "St. George's Bay watershed"
          href: "map_St.%20George%27s%20Bay.html"
        - text: "Poile Bay watershed"
          href: "map_La%20Poile%20Bay.html"
        - text: "White Bear Bay watershed"
          href: "map_White%20Bear%20Bay.html"
        - text: "Grey watershed"
          href: "map_Grey.html"
        - text: "Hermitage Bay watershed"
          href: "map_Hermitage%20Bay.html"
        - text: "Fortune Bay watershed"
          href: "map_Fortune%20Bay.html"
        - text: "Southwestern Placentia Bay watershed"
          href: "map_Southwestern%20Placentia%20Bay.html"
        - text: "Northwestern Placentia Bay watershed"
          href: "map_Northwestern%20Placentia%20Bay.html"
        - text: "Trinity Bay watershed"
          href: "map_Trinity%20Bay.html"
        - text: "Eastern Placentia and Western St. Mary's Bays watershed"
          href: "map_Eastern%20Placentia%20and%20Western%20St.%20Mary%27s%20Bays.html"
        - text: "Conception Bay watershed"
          href: "map_Conception%20Bay.html"
        - text: "Eastern Coast Newfoundland watershed"
          href: "map_Eastern%20Coast%20Newfoundland.html"
        - text: "Eastern St. Mary's Bay watershed"
          href: "map_Eastern%20St.%20Mary%27s%20Bay.html"
      - text: "Field data"
        href: Exploits_map.qmd 
      - text: "Sliders"
        href: Sliders.qmd 
      - text: "Resources"
        href: resources.qmd         
format:
  html:
    theme: sandstone
    css: styles.css
    toc: false


