---
title: "Sliders"
engine: knitr
theme: sandstone
format: 
  live-html:
    css: styles.css
    grid: 
      sidebar-width: 10px
      margin-width: 10px
      body-width: 1900px
execute:
  echo: false
  warning: false
  error: false
---


{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}
Set the below variable values to see predictions of several response variables shown in the bar graph.  
Description of the models can be found at the [bottom](#bottom) of each page.
```{r, load}
#| include: false
#| warning: false

pacman::p_load(shiny,
               bslib,
               ggplot2,
               ggtext,
               shinythemes,
               thematic,
               tidyverse,
               httr,
               htmltools,
               glue)
```

```{ojs}
//| echo: false
//| output: false


import {vl} from "@vega/vega-lite-api"
import { aq, op } from "@uwdata/arquero"


vg = require('vega-lite')

// references to images stored in data folder for each response variable
imageURL_invert = FileAttachment("/data/invert 2.png").url()
imageURL_peri = FileAttachment("/data/periphyton.png").url()
imageURL_gravel = FileAttachment("/data/gravel.png").url()
imageURL_par_len = FileAttachment("/data/par_len.png").url()

// function to convert all predictions that are negative to 0
function negativetozero(equation) { 
  return op.bin(equation, 0, op.greatest(equation), 0.0001)
}

```

::: {.panel-tabset}

## Invertebrate, periphyton and juvenile salmon estimates

```{ojs}
//| echo: false
//| panel: sidebar
// sliders for predictor variables


// example: periphyton biomass (mean - 1 outlier)
viewof peri = {
  const form = Inputs.range(
  [0, 0.5], 
  {value: 0.25, step: (0.5)/100, label: "Periphyton density (μg cm⁻²):"}
);
  form.range.style.cssText += "accent-color: #1f78b4; width: 500px";
  form.number.style.cssText += "color: #031D5E; background-color: #E4F3F7; border: 1px solid #031D5E; border-radius: 3px; text-align: right; padding: none";
    
  const label = form.querySelector("label");
  label.style.cssText += "width: 100%";
  
  return form;
}

// example: EPT
viewof EPT = {
  const form = Inputs.range(
  [0, 60], 
  {value: 30, step: 60/100, label: "Density of Ephemeroptera, Plecoptera, and Trichoptera (g m⁻²):"}
);
  form.range.style.cssText += "accent-color: #1f78b4; width: 500px";
  form.number.style.cssText += "color: #031D5E; background-color: #E4F3F7; border: 1px solid #031D5E; border-radius: 3px; text-align: right; padding: none";
  
  const label = form.querySelector("label");
  label.style.cssText += "width: 100%; margin-top: 10px";

  return form;
}   

```


```{ojs}
//| echo: false
//| panel: fill

// prediction functions
function invertbiomass(peri) {
  return negativetozero(1.133+5.50*peri)
}

function peribiomass(EPT) {
  return negativetozero(0.01 + 0.08*EPT) 
}

// error bar functions
function inverthigh(peri) {
  return negativetozero(1.133+0.19+(5.50+1.89)*peri)
}

function invertlow(peri) {
  return negativetozero(1.133-0.19+(5.50-1.89)*peri)
}

function perihigh(EPT) {
  return negativetozero((0.01+0.02)  + (0.08+0.02)*EPT) 
}

function perilow(EPT) {
  return negativetozero((0.01-0.02) + (0.08-0.02)*EPT) 
}


// function that takes input from sliders and creates prediction of each response variable
function myFunction(peri, EPT) {
  return aq.table({
  'peri': [peri, peri], // repeat for each input
  'EPT': [EPT, EPT],
  'response_type': ["Predicted invertebrate density (g m⁻²)", 
                    "Predicted periphyton density (μg cm⁻²)",
                    ], // ordered alphabetically
  'response_predict': [invertbiomass(peri),
                      peribiomass(EPT) // keep label normal
                      ],
  'response_errorhigh': [inverthigh(peri) ,
                        perihigh(EPT) 
                        ],
  'response_errorlow': [invertlow(peri) ,
                        perilow(EPT)
                        ]
  })
}

// create the table
predictions_ps = myFunction(peri, EPT)

// create a table that stores the image paths
images = aq.table({
  'response_type': ["Invertebrate biomass (g m⁻²)", 
                    "Periphyton biomass (μg cm⁻²)",
                    //"Invertebrate diversity", 
                    //"Par length (cm)"
                    ], // ordered alphabetically
  'image_path': [imageURL_invert, 
                  imageURL_peri
                  //imageURL_invert_div, 
                  //imageURL_par_len
                  ] //order these to match alphabetically ordered response variables (response_type)
})

// create the bar plot based on predictions_ps
Plot.plot({
  width: Math.max(width, 550),
  height: Math.floor(0.45 * width),
  marginLeft: 0,
  marginRight: 0,
  marginBottom: 70,
  color: {scheme: "dark2" ,
  legend: false},
  y: {domain: [0,10], axis: null},
  x: {label: null},
  marks:[
    Plot.axisX({fontSize: 25}), 
    Plot.barY(predictions_ps,
     {x: "response_type",
     y: "response_predict",
     fill: "response_type"}), // create bar graph
    Plot.text(predictions_ps, {x: "response_type", y: "response_predict", text: "response_predict", dy: -7, dx: -200, lineAnchor: "bottom", fontSize: 30}), // write out predicted value
    Plot.ruleX(predictions_ps, {x: "response_type", y1: 'response_errorlow', y2: 'response_errorhigh', strokeWidth: 3}) // add error bars
   ]
})

// add images below each bar
Plot.plot({
  width: Math.max(width, 550),
  height: Math.floor(0.1 * width),
  marginLeft: 0,
  marginRight: 0,
  colour: {legend: false},
  y: {domain: [0,0], axis: null},
  x: {label: "Response type", axis: null, fontSize: 22},
  marks:[
    Plot.image(images, 
      {x: "response_type",
      y: [0, 0, 0, 0],
      src: "image_path",
      width: 150,
      axis: null
      })
   ]
})
```
 
\

| The predictor variables, measured in field, were assessed for their correlation to invertebrate and periphyton biomass, using general linear models compared using Akaike’s Information Criterion corrected for small sample sizes.  



## Gravel and spawning estimates

```{ojs}
//| echo: false
//| panel: sidebar

// sliders for predictor variables

// example: discharge
viewof DIS_AV_CMS = {
  const form = Inputs.range(
  [0, 300], 
  {value: 1, step: 300/1000, label: "Discharge (units):"}
);
  form.range.style.cssText += "accent-color: #1f78b4; width: 500px";
  form.number.style.cssText += "color: #031D5E; background-color: #E4F3F7; border: 1px solid #031D5E; border-radius: 3px; text-align: right; padding: none";
    
  const label = form.querySelector("label");
  label.style.cssText += "width: 100%";

  return form;
}
// example: Stream width
viewof swidth = {
  const form = Inputs.range(
  [0, 100], 
  {value: 20, step: 100/100, label: "Stream width (m):"}
);
  form.range.style.cssText += "accent-color: #1f78b4; width: 500px";
  form.number.style.cssText += "color: #031D5E; background-color: #E4F3F7; border: 1px solid #031D5E; border-radius: 3px; text-align: right; padding: none";
  
  const label = form.querySelector("label");
  label.style.cssText += "width: 100%; margin-top: 10px";

  return form;
}
// example: Stream gradient
viewof sgr_dk_rav = {
  const form = Inputs.range(
  [0, 0.05], 
  {value: 0.0035, step: 0.05/100, label: "Stream gradient:"}
);
  form.range.style.cssText += "accent-color: #1f78b4; width: 500px";
  form.number.style.cssText += "color: #031D5E; background-color: #E4F3F7; border: 1px solid #031D5E; border-radius: 3px; text-align: right; padding: none";
  
  const label = form.querySelector("label");
  label.style.cssText += "width: 100%; margin-top: 10px";

  return form;
}
// example: fish length
viewof fish = {
  const form = Inputs.range(
  [0, 2], 
  {value: 1, step: 2/100, label: "Fish length (m):"}
);
  form.range.style.cssText += "accent-color: #1f78b4; width: 500px";
  form.number.style.cssText += "color: #031D5E; background-color: #E4F3F7; border: 1px solid #031D5E; border-radius: 3px; text-align: right; padding: none";
  
  const label = form.querySelector("label");
  label.style.cssText += "width: 100%; margin-top: 10px";

  return form;
}


```


```{ojs}
//| echo: false
//| panel: fill

// prediction functions
function gravelsize(DIS_AV_CMS, swidth, sgr_dk_rav) {
  return (2000 * op.pow(0.04, (3 / 5)) * op.pow((DIS_AV_CMS / swidth), (3 / 5)) * op.pow(sgr_dk_rav, (7 / 10)) / (650 * 0.04)) * 1000 ;
}


// to get normal distribution that skews at limits of suitable gravel

//function f(x) { 
//  return op.exp(((-1 / 2) * op.pow(((x) /4), 2)))
//}

//erf = (await import("https://cdn.jsdelivr.net/npm/@stdlib/esm@0.0.3/math/base/special/erf.js"))
//  .default

//function P(x) { 
//  return (1/2) * (1 + erf(x / op.sqrt(2)))
//}

// shape of curve responds to ideal gravel size for fish length (linear function)
//function a(i) {
//  return (((-2/48)*i)+1.67)*10
//}

// ideal fish size as exponential growth, where 16 is ideal for 0.1 m fish and 64 is ideal for 2m fish

function idealsize(fish) {
  return 109 * (op.pow(1.26, fish) - 1)
}

//function spawningprob(DIS_AV_CMS, swidth, sgr_dk_rav, fish) {
//  return f((gravelsize(DIS_AV_CMS, swidth, sgr_dk_rav) - idealsize(fish)) / 2) * P(a(idealsize(fish)) * ((gravelsize(DIS_AV_CMS, swidth, sgr_dk_rav) - idealsize(fish)) / 2));
//}


function spawningprob(DIS_AV_CMS, swidth, sgr_dk_rav, fish) {
  if(16 <= gravelsize(DIS_AV_CMS, swidth, sgr_dk_rav) <=64) {
  return op.exp((-1/2) * (op.pow((gravelsize(DIS_AV_CMS, swidth, sgr_dk_rav) - idealsize(fish))/8, 2)));
  } else {
  return 0
  }
}



// function that takes input from sliders and creates prediction of each response variable

function gravelFunction(DIS_AV_CMS, swidth, sgr_dk_rav, fish) {
  return aq.table({
  'DIS_AV_CMS': [DIS_AV_CMS, DIS_AV_CMS], // repeat for each input
  'swidth': [swidth, swidth],
  'sgr_dk_rav':[sgr_dk_rav, sgr_dk_rav],
  'fish': [fish, fish],
  'response_type': ["Predicted gravel size (D50; mm)", 
                    "Suitability of predicted gravel size for \nspawning by salmon of given length" //not sure what this variable will be yet
                    ], // ordered alphabetically
                      
  'response_predict': [gravelsize(DIS_AV_CMS, swidth, sgr_dk_rav),
                        spawningprob(DIS_AV_CMS, swidth, sgr_dk_rav, fish)*2000
                      ],
  'response_predict_label': [gravelsize(DIS_AV_CMS, swidth, sgr_dk_rav),
                        spawningprob(DIS_AV_CMS, swidth, sgr_dk_rav, fish)
                      ]
  })
}

// create the table
predictions_gravel = gravelFunction(DIS_AV_CMS, swidth, sgr_dk_rav, fish)

// create a table that stores the image paths
images2 = aq.table({
  'response_type': ["Gravel size D50 (m)", 
                    "Probability salmon spawn in predicted gravel size",
                    ], // ordered alphabetically
  'image_path': [imageURL_gravel, 
                  imageURL_par_len
                  ] //order these to match alphabetically ordered response variables (response_type)
})

// create the bar plot based on predictions_ps
Plot.plot({
  width: Math.max(width, 550),
  height: Math.floor(0.45 * width),
  marginLeft: 0,
  marginRight: 0,
  marginBottom: 70,
  color: {scheme: "dark2" ,
  legend: false},
  y: {domain: [0, 2000], label: null},
  x: {label: null},
  marks:[
    Plot.axisX({fontSize: 25, marginBottom: 40}),
    Plot.barY(predictions_gravel,
     {x: "response_type",
     y: "response_predict",
     fill: "response_type"}), // create bar graph
    Plot.text(predictions_gravel, {x: "response_type", y: "response_predict", text: "response_predict_label", dy: -7, dx: -200, lineAnchor: "bottom", fontSize: 30}) // write out predicted value
   ]
})

// add images below each bar
Plot.plot({
  width: Math.max(width, 550),
  height: Math.floor(0.1 * width),
  marginTop: 20,
  marginLeft: 0,
  marginRight: 0,
  colour: {legend: false},
  y: {domain: [0,0], axis: null},
  x: {label: "Response type", axis: null, fontSize: 22},
  marks:[
    Plot.image(images2, 
      {x: "response_type",
      y: [0, 0],
      src: "image_path",
      width: 150,
      axis: null
      })
   ]
})
```


\

| Gravel size was predicted based on the following calculations (Wilkins & Snyder 2011)
| 
| D50 = 𝛕<sub>b</sub> / (𝛒<sub>s</sub> - 𝛒) * g * 𝛕<sup>* </sup>
| 
| Parameters:
| 𝛕<sub>b</sub> = 𝛒 * g * n<sup>3/5</sup> * [Q/W]<sup>3/5</sup> * S<sup>7/10</sup>
| 𝛒 = density of water = 1000 kg/m<sup>3</sup>
| g = acceleration by gravity = 9.80665 m/s<sup>2</sup>
| n = channel roughness coefficient = n = 0.04 as estimate for gravel bed rivers from Barnes 1967
| 𝛒<sub>s</sub> = sediment density = 2650 kg/m<sup>3</sup>
| <sup>*</sup>  =  Shields parameter = 0.04 to follow Wilkins & Snyder 2011
| 
| Variables to retreive from HydroSHEDs:
| S = channel gradient, Calculated as the ratio between the elevation drop within the river reach (i.e. the difference between min. and max. elevation along the reach) and the length of the reach.
| Q = Discharge (m<sup>3</sup>/s), Average long-term discharge estimate for river reach, in cubic meters per second.
| W = channel width (m), Calculated as the surface river area of the river reach segment divided by length of the river reach segment.
|  
| 
| Spawning suitability in predicted gravel size  for fish of chosen length (m) calculated using the following equation:
| 
| Suitability = e<sup>((-1/2) * ((D50 - ideal.fish.gravel)/8)<sup>2</sup>)</sup>
| 
| Ideal.fish.gravel = 109 * (1.26<sup>fish.length</sup> - 1)
| 
| This equation associates a higher probability of spawning in larger gravel for longer fish, and a higher probability of spawning in smaller gravel for smaller fish.  
| Assumes the ideal spawning gravel for a fish of 2m is 64 mm,  for a fish of 1 m is 32 mm, for a fish of 0 m is 16 mm etc, with a bell shaped distribution of suitability around the ideal gravel size with a standard deviation of 8. If D50 is lower than 16 or higher than 64, the suitability is 0.
|

:::
<div id="bottom"></div>